pipeline {
  agent any
  stages {
    stage('Checkout SCM') {
      steps {
        checkout scm
      }
    }
    stage('Maven Install') {
      steps {
        script {
          // Use Maven installed on the Jenkins server with the system JDK (OpenJDK 21)
          sh 'mvn clean install'
        }
      }
    }
    stage('Docker Build') {
      steps {
        script {
          // Assuming your Dockerfile is in the root of the repo
          sh 'docker build -t vikasghandge/spring-petclinic:latest .'
        }
      }
    }
  }
}
