pipeline {
  agent any
  stages {
    stage('Maven Install') {
      agent {
        docker {
          image 'maven:3.8.7-openjdk-17' 
           // Use the valid Maven image with JDK 17
        }
      }
      steps {
        dir('spring-petclinic-main') {
          sh 'mvn clean install'
        }
      }
    }
    stage('Docker Build') {
      agent any
      steps {
        dir('spring-petclinic-main') {
          sh 'docker build -t vikasghandge/spring-petclinic:latest .'
        }
      }
    }
  }
}
