FROM nginx:alpine

COPY  season.html /usr/share/nginx/html/index.html
COPY season.css /usr/share/nginx/html/
COPY counter.js /usr/share/nginx/html/

EXPOSE 80

#CMD [ "nginx" "-g" "dameon off;" ]
CMD ["nginx", "-g", "daemon off;"]

