FROM ubuntu:latest
LABEL ubuntu="latest"

RUN apt update && \
    apt install nginx unzip -y && \
    rm -rf /usr/share/nginx/html/index.html

COPY oxer.zip /usr/share/nginx/html/
WORKDIR /usr/share/nginx/html/
RUN unzip oxer.zip && \
    mv oxer-html/* . && \
    rm -rf oxer-html oxer.zip

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
