services:
  nginxfrontendconone:
      build: .
      ports: 
          - '81:81'
      network_mode: bridge
      container_name: frontend1
      volumes: 
         - myapp:/usr/share/nginx/html/
      networks:
         - myappnetwork

#   nginxfrontendcontwo:
#       build: . 
#       network_mode: host
#       container_name: frontend2
#       volumes: 
#         - myapp2:/usr/share/nginx/html/
#       networks:
#          - myappnetwork

# volumes:   # Will create a volume for you.
#       myapp:
#       myapp2:

# networks:
#   myappnetwork:
