
#choosed base image ubuntu
FROM ubuntu:latest

# tags
LABEL purpose="backend"

# change directory
WORKDIR /opt

# adding tomcat into /opt directory # ADD 
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.93/bin/apache-tomcat-9.0.93.zip /opt

