
#choosed base image ubuntu
FROM ubuntu:latest

# tags
LABEL purpose="backend"

# change directory
WORKDIR /opt

# adding tomcat into /opt directory # ADD command add form remote location
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.93/bin/apache-tomcat-9.0.93.zip /opt

# run some essential command 
RUN apt update && \
apt install unzip openjdk-11-jdk -y && \
unzip apache-tomcat-9.0.93.zip

ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war  dest

