# Base image
FROM ubuntu:latest

# Tags
LABEL purpose="backend"

# Set the working directory
WORKDIR /opt

# Add Tomcat zip to /opt directory
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.93/bin/apache-tomcat-9.0.93.zip /opt

# Install required packages and unzip Tomcat
RUN apt update && \
    apt install -y unzip openjdk-11-jdk && \
    unzip apache-tomcat-9.0.93.zip && \
    rm apache-tomcat-9.0.93.zip

# Add student.war to Tomcat webapps directory
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war apache-tomcat-9.0.93/webapps/

# Add MySQL connector to Tomcat lib directory
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar apache-tomcat-9.0.93/lib

# Copy context.xml into Tomcat conf directory
COPY context.xml apache-tomcat-9.0.93/conf/

# Add execution permissions to catalina.sh
RUN chmod +x /opt/apache-tomcat-9.0.93/bin/*.sh

# Expose port 8080 for Tomcat
EXPOSE 8080

# Start Tomcat
CMD ["/opt/apache-tomcat-9.0.93/bin/catalina.sh", "run"]
