# Use the Nginx Alpine image as the base
FROM nginx:alpine

# Copy the static website files to the Nginx default HTML directory
COPY . /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 81

# Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
