FROM ubuntu:latest
LABEL image="frontend-setup"
RUN apt update 
RUN apt-get install nginx unzip -y
COPY carvilla.zip /var/www/html
WORKDIR /var/www/html/
RUN unzip carvilla.zip
RUN mv carvilla/* .
EXPOSE 80
CMD [ "systemctl" "g" "daemon-off"]




