FROM ubuntu:latest
LABEL image="frontend-setup"
RUN apt update 
RUN install nginx unzip -y
COPY carvilla.zip /var/www/html
WORKDIR /var/www/html/
RUN unzip carvilla.zip
RUN mv carvilla-html/* .
EXPOSE 80
CMD [ "sys" ]




