FROM ubuntu:latest
LABEL image="frontend-setup"
RUN apt update 
RUN apt-get install nginx unzip -y
COPY carvilla.zip /var/www/html
WORKDIR /var/www/html/
RUN unzip carvilla.zip
RUN mv carvilla-v1.0/* .
EXPOSE 80
#CMD [ "nginx" "-g" "daemon off;"]
CMD ["nginx", "-g", "daemon off;"]
nginx -g "daemon off;"




