version: '3'
services:
  todo:
    build: ./todo
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  trafficlight:
    build: ./trafficlight
    ports:
      - "3001:3001"
    networks:
      - mynetwork

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
