version: '3'
services:
  todo:
    build:
      context: .
      dockerfile: dockerfile.todo
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  traffic_light:
    build:
      context: .
      dockerfile: dockerfile.traffic_light
    ports:
      - "3001:3001"
    networks:
      - mynetwork

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
