FROM nginx:latest
COPY traffic_light.html /usr/share/nginx/html/index.html
#COPY traffic_light.css /usr/share/nginx/html/
#COPY traffic_light.js /usr/share/nginx/html/

EXPOSE 8082

CMD ["nginx", "-g", "daemon off;"]
