FROM nginx:latest

# Copy your HTML file to the correct location
COPY traffic_light.html /usr/share/nginx/html/index.html

# Expose port 8082
EXPOSE 8082

# Create a custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
